/**
 * Lead Price Index — Q3 research brief generator.
 *
 * The Price Index is a quarterly *human-verified* study (see
 * `app/api/cron/marketwatch/route.ts:156` and the 2026-06-09 repositioning).
 * Nothing auto-publishes benchmarks and nothing in this script does either —
 * it produces the *research brief* that makes the human study tractable:
 * exactly which cells need re-pricing, which providers already showed a
 * pricing signal this cycle, and which verticals are one month away from
 * turning their trend chart back on.
 *
 * Why this exists: `data/loop/README.md` — a derived artifact assembled by
 * hand goes stale with no signal. Regenerate with `npm run price-index:gap`.
 *
 * Reads only. Writes one markdown file. No Sanity token required — the
 * production dataset is world-readable.
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const PROJECT_ID = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID ?? "p7rbtajg";
const DATASET = process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production";

/** `components/price-trend-chart.tsx:53` returns null below this. */
const TREND_CHART_MIN_MONTHS = 3;
/** `lib/benchmark-coverage.ts` trust gate — single-provider rows are junk. */
const MIN_PROVIDERS = 2;

const REPORTS_DIR = join(process.cwd(), "data", "marketwatch-reports");
const OUT_PATH = join(process.cwd(), "data", "loop", "price-index-q3-gap.md");

interface Benchmark {
  vertical: string;
  month: string;
  leadAgeBracket: string;
  exclusivity: string;
  leadType: string;
  priceLow: number;
  priceMedian: number;
  priceHigh: number;
  providersSampled: number | null;
  confidence: string | null;
}

interface RawPricing {
  vertical?: string;
  leadType?: string;
  ageBracket?: string;
  priceRange?: string;
}

interface ProviderUpdate {
  providerSlug: string;
  providerName: string;
  pricingChanges?: string[];
  rawPricingData?: (RawPricing | string)[];
}

async function fetchBenchmarks(): Promise<Benchmark[]> {
  const query = `*[_type=="priceBenchmark"]{
    month, leadAgeBracket, exclusivity, leadType,
    priceLow, priceMedian, priceHigh, providersSampled, confidence,
    "vertical": vertical->slug.current
  }`;
  const url =
    `https://${PROJECT_ID}.api.sanity.io/v2023-05-03/data/query/${DATASET}` +
    `?query=${encodeURIComponent(query)}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Sanity ${res.status}: ${await res.text()}`);
  const body = (await res.json()) as { result?: Benchmark[] };
  if (!body.result) throw new Error("Sanity returned no result set");
  return body.result.filter((b) => b.vertical);
}

function loadProviderSignals(): Map<string, ProviderUpdate[]> {
  const byMonth = new Map<string, ProviderUpdate[]>();
  for (const file of readdirSync(REPORTS_DIR).sort()) {
    if (!file.endsWith(".json")) continue;
    const month = file.replace(/\.json$/, "");
    const report = JSON.parse(readFileSync(join(REPORTS_DIR, file), "utf8"));
    const updates: ProviderUpdate[] = report.providerUpdates ?? [];
    byMonth.set(
      month,
      updates.filter(
        (u) => (u.pricingChanges?.length ?? 0) > 0 || (u.rawPricingData?.length ?? 0) > 0
      )
    );
  }
  return byMonth;
}

const cellKey = (b: Benchmark) =>
  `${b.leadAgeBracket} | ${b.exclusivity} | ${b.leadType}`;

function main(benchmarks: Benchmark[], signals: Map<string, ProviderUpdate[]>) {
  const reliable = benchmarks.filter(
    (b) => (b.providersSampled ?? 0) >= MIN_PROVIDERS
  );

  const monthsByVertical = new Map<string, Set<string>>();
  for (const b of reliable) {
    if (!monthsByVertical.has(b.vertical)) monthsByVertical.set(b.vertical, new Set());
    monthsByVertical.get(b.vertical)!.add(b.month);
  }

  const latestMonth = reliable.length
    ? reliable.map((b) => b.month).sort().at(-1)!
    : "(none)";

  const verticals = [...monthsByVertical.keys()].sort();
  const out: string[] = [];

  out.push("# Lead Price Index — Q3 research brief");
  out.push("");
  out.push(
    "> Generated by `npm run price-index:gap`. Do not edit by hand — regenerate."
  );
  out.push("");
  out.push(
    "The Price Index is a **quarterly human-verified study**. This brief does not " +
      "estimate prices and no script publishes benchmarks; it scopes the research so " +
      "the study is a checklist instead of an open-ended dig."
  );
  out.push("");
  out.push(`- Benchmark documents in Sanity: **${benchmarks.length}**`);
  out.push(
    `- Clearing the ${MIN_PROVIDERS}-provider trust gate: **${reliable.length}**`
  );
  out.push(`- Latest reliable month: **${latestMonth}**`);
  out.push("");

  // ── Trend-chart unlock ────────────────────────────────────────────
  out.push("## The unlock: trend charts");
  out.push("");
  out.push(
    `\`components/price-trend-chart.tsx\` renders nothing below **${TREND_CHART_MIN_MONTHS} reliable months**. ` +
      "One more verified month per vertical is the difference between a price page with a chart and one without."
  );
  out.push("");
  out.push("| vertical | reliable months | has chart | months needed |");
  out.push("|---|---:|:---:|---:|");
  let unlockCount = 0;
  for (const v of verticals) {
    const n = monthsByVertical.get(v)!.size;
    const has = n >= TREND_CHART_MIN_MONTHS;
    const needed = Math.max(0, TREND_CHART_MIN_MONTHS - n);
    if (needed === 1) unlockCount++;
    out.push(`| \`${v}\` | ${n} | ${has ? "yes" : "**no**"} | ${needed || "—"} |`);
  }
  out.push("");
  out.push(
    `**${unlockCount} vertical(s) are exactly one verified month away from a trend chart.**`
  );
  out.push("");

  // ── Per-vertical cell checklist ───────────────────────────────────
  out.push("## What to re-price, by vertical");
  out.push("");
  out.push(
    "Each vertical's most recent reliable month, broken into the cells that month covered. " +
      "Re-observing the same cells keeps the trend series comparable — a chart built from " +
      "different cells month to month is measuring the cell mix, not the market."
  );
  out.push("");
  for (const v of verticals) {
    const rows = reliable.filter((b) => b.vertical === v);
    const newest = rows.map((b) => b.month).sort().at(-1)!;
    const cells = rows.filter((b) => b.month === newest);
    out.push(`### \`${v}\` — last verified ${newest}`);
    out.push("");
    out.push("| age bracket | exclusivity | lead type | low | median | high | providers |");
    out.push("|---|---|---|---:|---:|---:|---:|");
    for (const c of cells.sort((a, b) => cellKey(a).localeCompare(cellKey(b)))) {
      out.push(
        `| ${c.leadAgeBracket} | ${c.exclusivity} | ${c.leadType} | ` +
          `$${c.priceLow} | $${c.priceMedian} | $${c.priceHigh} | ${c.providersSampled ?? "?"} |`
      );
    }
    out.push("");
  }

  // ── Collected signals ─────────────────────────────────────────────
  out.push("## Pricing signals already collected");
  out.push("");
  out.push(
    "`marketwatch` monitors provider sites monthly and records observed pricing. These are " +
      "**leads for the research, not benchmarks** — a single provider's published price does not " +
      "clear the trust gate on its own. Verify against the live site before using."
  );
  out.push("");
  for (const [month, updates] of [...signals.entries()].sort()) {
    out.push(`### ${month} — ${updates.length} provider(s) with signals`);
    out.push("");
    if (updates.length === 0) {
      out.push("_No signals collected. (2026-07 was the retired-model crash.)_");
      out.push("");
      continue;
    }
    for (const u of updates) {
      out.push(`**${u.providerName}**`);
      for (const raw of u.rawPricingData ?? []) {
        if (typeof raw === "string") {
          out.push(`- ${raw}`);
        } else {
          const parts = [raw.vertical, raw.ageBracket, raw.leadType]
            .filter(Boolean)
            .join(" / ");
          out.push(`- ${parts || "unspecified"} — **${raw.priceRange ?? "?"}**`);
        }
      }
      out.push("");
    }
  }

  writeFileSync(OUT_PATH, out.join("\n"));
  console.log(`Wrote ${OUT_PATH}`);
  console.log(
    `${reliable.length}/${benchmarks.length} reliable benchmarks; ` +
      `${unlockCount} vertical(s) one month from a trend chart.`
  );
}

fetchBenchmarks()
  .then((benchmarks) => main(benchmarks, loadProviderSignals()))
  .catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  });
