import { defineField, defineType } from "sanity";

export const leadProviderType = defineType({
  name: "leadProvider",
  title: "Lead Provider",
  type: "document",
  groups: [
    { name: "profile", title: "Profile", default: true },
    { name: "ratings", title: "Ratings" },
    { name: "operations", title: "Operations" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    // ── Profile ──────────────────────────────────────────────
    defineField({
      name: "name",
      title: "Provider Name",
      type: "string",
      group: "profile",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "profile",
      options: { source: "name", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      rows: 3,
      group: "profile",
      description: "One-liner for cards and listings",
      validation: (rule) => [
        rule.required(),
        rule.max(200).warning("Keep under 200 characters"),
      ],
    }),
    defineField({
      name: "logo",
      title: "Logo",
      type: "image",
      group: "profile",
      options: { hotspot: true },
    }),
    defineField({
      name: "website",
      title: "Website",
      type: "url",
      group: "profile",
    }),
    defineField({
      name: "foundedYear",
      title: "Founded Year",
      type: "number",
      group: "profile",
      validation: (rule) => rule.min(1900).max(2030),
    }),
    defineField({
      name: "bbbRating",
      title: "BBB Rating",
      type: "string",
      group: "profile",
      options: {
        list: [
          { title: "A+", value: "A+" },
          { title: "A", value: "A" },
          { title: "A-", value: "A-" },
          { title: "B+", value: "B+" },
          { title: "B", value: "B" },
          { title: "B-", value: "B-" },
          { title: "C", value: "C" },
          { title: "Not Rated", value: "NR" },
        ],
      },
    }),
    defineField({
      name: "headquartersState",
      title: "Headquarters State",
      type: "string",
      group: "profile",
    }),
    defineField({
      name: "body",
      title: "Editorial Review",
      type: "array",
      group: "profile",
      description: 'Our honest editorial review — include "Best for:" and "Not ideal for:" sections',
      of: [
        { type: "block" },
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            { name: "alt", type: "string", title: "Alt Text" },
            { name: "caption", type: "string", title: "Caption" },
          ],
        },
      ],
    }),
    defineField({
      name: "bestFor",
      title: "Best For",
      type: "array",
      group: "profile",
      description: 'e.g. "Beginners", "High Volume", "Insurance Agents"',
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "notIdealFor",
      title: "Not Ideal For",
      type: "array",
      group: "profile",
      description: 'e.g. "Low budget buyers", "Enterprise API needs"',
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),

    // ── Ratings ──────────────────────────────────────────────
    defineField({
      name: "ratingTransparency",
      title: "Pricing Transparency (20%)",
      type: "number",
      group: "ratings",
      description: "1-10: Are prices published? Self-service purchasing?",
      validation: (rule) => rule.min(1).max(10),
    }),
    defineField({
      name: "ratingValue",
      title: "Value (20%)",
      type: "number",
      group: "ratings",
      description: "1-10: Price relative to reported quality and contact rates",
      validation: (rule) => rule.min(1).max(10),
    }),
    defineField({
      name: "ratingCompliance",
      title: "Data Quality & Compliance (20%)",
      type: "number",
      group: "ratings",
      description: "1-10: TCPA documentation handoff, DNC scrubbing, data verification and hygiene, operational discipline",
      validation: (rule) => rule.min(1).max(10),
    }),
    defineField({
      name: "ratingFlexibility",
      title: "Flexibility (15%)",
      type: "number",
      group: "ratings",
      description: "1-10: Minimums, contracts, return policy, filtering options",
      validation: (rule) => rule.min(1).max(10),
    }),
    defineField({
      name: "ratingPlatform",
      title: "Platform & Delivery (15%)",
      type: "number",
      group: "ratings",
      description: "1-10: Self-service, CRM integration, API, instant delivery",
      validation: (rule) => rule.min(1).max(10),
    }),
    defineField({
      name: "ratingReputation",
      title: "Reputation & Track Record (10%)",
      type: "number",
      group: "ratings",
      description: "1-10: Years in business, BBB, industry presence, forum sentiment",
      validation: (rule) => rule.min(1).max(10),
    }),
    defineField({
      name: "ratingNotes",
      title: "Rating Notes",
      type: "text",
      rows: 4,
      group: "ratings",
      description: "Internal notes on rating rationale",
    }),
    defineField({
      name: "lastVerified",
      title: "Last Verified",
      type: "date",
      group: "ratings",
      description: "When this profile was last reviewed and verified for accuracy",
      validation: (rule) => rule.required(),
    }),

    // ── Operations ───────────────────────────────────────────
    defineField({
      name: "verticals",
      title: "Verticals Served",
      type: "array",
      group: "operations",
      of: [{ type: "reference", to: [{ type: "vertical" }] }],
    }),
    defineField({
      name: "leadTypes",
      title: "Lead Types Offered",
      type: "array",
      group: "operations",
      of: [{ type: "string" }],
      options: {
        list: [
          { title: "Aged Internet Leads", value: "aged" },
          { title: "Real-Time Internet Leads", value: "real-time" },
          { title: "Live Transfers", value: "live-transfer" },
          { title: "Trigger / Credit Pulls", value: "trigger" },
          { title: "Data Lists", value: "data-list" },
          { title: "Direct Mail Leads", value: "direct-mail" },
        ],
      },
    }),
    defineField({
      name: "pricingModel",
      title: "Pricing Model",
      type: "string",
      group: "operations",
      options: {
        list: [
          { title: "Transparent — prices published online", value: "transparent" },
          { title: "Semi-Transparent — ranges published, exact quotes require contact", value: "semi-transparent" },
          { title: "Sales Required — must contact for pricing", value: "sales-required" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "hasMinimums",
      title: "Has Minimum Order?",
      type: "boolean",
      group: "operations",
      initialValue: false,
    }),
    defineField({
      name: "minimumDescription",
      title: "Minimum Order Details",
      type: "string",
      group: "operations",
      description: 'e.g. "100 leads minimum", "No minimums"',
      hidden: ({ parent }) => !parent?.hasMinimums,
    }),
    defineField({
      name: "contractRequired",
      title: "Contract Required?",
      type: "boolean",
      group: "operations",
      initialValue: false,
    }),
    defineField({
      name: "returnPolicy",
      title: "Return / Refund Policy",
      type: "string",
      group: "operations",
      description: 'e.g. "Up to 20% return cap for wrong numbers", "All sales final"',
    }),
    defineField({
      name: "deliveryMethods",
      title: "Delivery Methods",
      type: "array",
      group: "operations",
      of: [{ type: "string" }],
      options: {
        list: [
          { title: "Instant Download / CSV", value: "instant-download" },
          { title: "Email Delivery", value: "email" },
          { title: "API Integration", value: "api" },
          { title: "CRM Push", value: "crm-push" },
          { title: "Real-Time Post", value: "real-time-post" },
        ],
      },
    }),
    defineField({
      name: "complianceFeatures",
      title: "Compliance Features",
      type: "array",
      group: "operations",
      of: [{ type: "string" }],
      options: {
        list: [
          { title: "TCPA Documentation Handoff", value: "tcpa-docs" },
          { title: "DNC Scrubbing", value: "dnc-scrubbing" },
        ],
      },
    }),
    defineField({
      name: "affiliateUrl",
      title: "Affiliate URL",
      type: "url",
      group: "operations",
      description: "Tracked link if we have an affiliate relationship",
    }),
    defineField({
      name: "isFeatured",
      title: "Featured Provider?",
      type: "boolean",
      group: "operations",
      initialValue: false,
    }),

    // ── SEO ──────────────────────────────────────────────────
    defineField({
      name: "seo",
      title: "SEO",
      type: "object",
      group: "seo",
      fields: [
        defineField({
          name: "metaTitle",
          title: "Meta Title",
          type: "string",
          validation: (rule) =>
            rule.max(60).warning("Keep under 60 characters"),
        }),
        defineField({
          name: "metaDescription",
          title: "Meta Description",
          type: "text",
          rows: 3,
          validation: (rule) =>
            rule.max(160).warning("Keep under 160 characters"),
        }),
      ],
      options: { collapsible: true, collapsed: true },
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "shortDescription",
      media: "logo",
    },
  },
  orderings: [
    {
      title: "Name",
      name: "nameAsc",
      by: [{ field: "name", direction: "asc" }],
    },
  ],
});
